### PR TITLE
Cross-Platform Notification Update: Introducing Windows Support

### PR DESCRIPTION
**Pull request by reginaldosnunes**
#3 Windows Support

A PowerShell script has been incorporated, utilizing native Windows resources for displaying notifications. Additionally, necessary libraries have been added to enable access to the script.

### CODE REVIEW

**Comment by brunocroh** [comment]
@reginaldosnunes I created the PR to your repo/branch with solution of move files.

I move the power shell script to folder lib, could you please update to works with file in that directory?

Thank you for your PR, I really appreciate it.

https://github.com/reginaldosnunes/notify-me/pull/1

**Comment by reginaldosnunes** [comment]
@brunocroh Sure, I'll do that.
Thanks for resolving this issue in my implementation.

**Comment by brunocroh** [comment]
When this PR is ready to merge let me know @reginaldosnunes

**Comment by reginaldosnunes** [comment]
@brunocroh The PR is ready to merge.

**Pull request merged**
